/** @format */
"use client";
import { type Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
  SignIn,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthPage from "@/components/AuthPage";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Clerk Next.js Quickstart",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname() || "";
  const isGuestPage = pathname.startsWith("/s/");
  console.log("pathname:", pathname, "isGuestPage:", isGuestPage);
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {isGuestPage ? (
            // Guest link: render page directly
            <>{children}</>
          ) : (
            <>
              {/* Signed-in content */}
              <SignedIn>
                <header className="h-16 flex items-center justify-between px-6 bg-gradient-to-r from-purple-600 to-indigo-600 shadow-md">
                  <h1 className="text-xl font-bold text-white tracking-wide">
                    Chatto
                  </h1>
                  <UserButton afterSignOutUrl="/" />
                </header>
                <div className="flex flex-col h-screen">
                  <div className="flex-1 overflow-auto">{children}</div>
                </div>
              </SignedIn>

              {/* Signed-out: show AuthPage */}
              <SignedOut>
                <AuthPage />
              </SignedOut>
            </>
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}
